#!/bin/bash

$ nano .bashrc

# alias for update
alias update='sudo apt update && sudo apt list upgradable && sudo apt upgrade -y && sudo apt install - y && sudo apt upgrade -y'
#alias for cleaning
alias clean='sudo apt autpremove && sudo apt autoclean'
