#!/bin/bash

$ nano .bashrc

# alias for update
alias update='sudo apt update --noconfirm --needed'
alias list='sudo apt --list upgradable --noconfirm --needed'
alias upgrade='sudo apt upgrade --noconfirm --needed'
alias cleaninst='sudo apt install && sudo apt upgrade --noconfirm --needed'